### PR TITLE
QA Service

### PR DESCRIPTION
**Pull request by llotneb**
This request will add a working version of question-answer to the command center branch of this repo. To test, clone the repo, checkout qa, then follow the instructions in qa/template and/or qa/sirius to build and run the service.

### CODE REVIEW

**Comment by jhauswald** [comment]
:+1:

**Comment by cdmeister** [comment]
https://google-styleguide.googlecode.com/svn/trunk/cppguide.html

**Build System**
*consider moving `java-config.sh` script into the common folder. 
*In the README, make sure to tell the user that a copy of thrift source code is required and they must build the java libraries by going into the thirft/libs/java and type `ant`
   *change the location in `java-config.sh` as well to point to the new location
*add the thrift command into Makefile so when the user types make, it generates the gen-java/gen-cpp folder. It is just one less step.
*Consider trying to minimize the build and compiling system. for template combine the client stuff and server compiling into one script. 

I ended up diverting from the readme because it did not address local needs. I assumed that you kept clarity04 in mind since everything is setup there. Take a look at the original sirius build system and see if you can draw any ideas. Make sure you address dependencies, I made an openCV script but make sure you aren't missing anything else. 

**Template**
QADaemon: indenting is off. tabs must equal to 2 spaces. I checked in vim and in gedit. 
QAClient: besides indenting, ok
test-concurrency-qa.sh: get rid of the '&' so the user can see step by step how the qa works rather than having a bunch of junk spit out at the screen at random times depending on what process is being executed. 
QAServiceHandler.java:Every function declaration should have comments immediately preceding it that describe what the function does and how to use it. (google style and I agree). fix indenting 

pick a {} style and be consistent 
keep some of the lines of code less than 80 characters (ex: QAClient.cpp)

**Sirius**
QADaemon& QAServiceHandler: same as above.

it registers with the command centre, but not sure if can receive requests and whatnot.

**Comment by llotneb** [comment]
Thanks for your comments Moeiz!
I hadn't looked at the google style guide before the pull request, so I'll read through it and make those changes. Also, I appreciate your running my code on another system, and I'll update the readmes to be more helpful.

The test-concurrency script was originally designed as a quick test to see how OpenEphyra would respond to multiple queries at the same time. Since OpenEphyra isn't currently a multithreaded program, I suppose I can just delete the script for now.

java-config.sh is in the top level directory, because I thought we might add other java services in the future. If so, the script can be modified to include additional global settings. Users would only have to modify the java-config file for their java services to find the appropriate libraries.

The compile-qa.sh script should automatically build the gen-java/gen-cpp files for you, as well as anything else you might need. I agree that java ant is more portable, but for this release, I'm hoping that shell scripts will be enough.

I divided the build system into multiple files, because the compilation/runtime classpaths for both versions of question-answer are almost the same. Therefore, I reasoned that it would be easier to just modify the shared classpaths in one place (common) than in several. I'm assuming that regular users would not need to modify anything in the common directory.

We can talk more about this over e-mail.

**Comment by cdmeister** [comment]
Hey,

You can keep the test-concurrency script if you want to send more than one query is sent. 

When we have a build system, java-config.sh would be integrated but only openephyra is the only one so probably just put it in the common folder

Multiple compile steps is kind of cumbersome for me.

**Pull request closed without merging**
