### PR TITLE
ASR Kaldi fixed f

### PR DESCRIPTION
**Pull request by cdmeister**
I fixed the asr branch to fit to our standards i think

### CODE REVIEW

**Comment by cdmeister** [comment]
Try following the directions on the readme and see if it works as well

**Comment by twurman** [comment]
- prepare was fine, compiled fine, and template test worked. 
- common folder didn't have anything checked in that shouldn't be there

### sirius folder
- client: remove client
- server: needs a style makeover. Indentation is completely inconsistent, missing spacing around operators, and inconsistent bracing style
- server: prints "Using default port for asr..." when you give it 3 arguments
- server: Tried to run with command center and got "Segmentation fault (core dumped)". Followed all steps in readme
- Makefile: rewrites CC_DIR object. Note that your branch does not have the current version of Makefile.config, so the CC_DIR path in config is incorrect. Should use CC_DIR from config
- Makefile: does not use CC_DIR path in CMDOBJECT_SERVER, but should 
- readme: not sure what this sentence means "In the first one, start up the serve with this command:"
- readme: remove part about openephrya

### template folder
- client: tiny fix with indentation
- client: fix spacing around operators (<<)
- client: using namespace std means you don't need to use std:: for cout and cerr. remove std:: qualifiers
- server: same style fixes as above
- readme: same as above

**Comment by cdmeister** [comment]
I forgot is there a style guide line we should be using?

**Comment by twurman** [comment]
https://google-styleguide.googlecode.com/svn/trunk/cppguide.html for now

**Comment by cdmeister** [comment]
How did you get the segfault, was it when you supplied the two port numbers?

**Comment by cdmeister** [comment]
I applied the changes and please take a look. And try to replicate the segfault.

**Comment by twurman** [comment]
Looks a lot better. The member function definitions in the two Kaldi_Server.cpp files should be aligned with the class definition though.
ex.

```
My_Class {
  void func1();
}
My_Class::func1(){
  //blah blah
}
```

No longer getting segfault. Tested with both 1 input and 2

Fix the little style issue and I'll sign off on a pull req to clarityinc

**Pull request closed without merging**
